// client/src/app/planner/components/goal-selector/goal-selector.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { RequirementSet } from '../../models/requirement-set.model';
import { RequirementService } from '../../services/requirement.service';

import { GoalSelectionState } from './selection-state';

@Component({
  selector: 'app-goal-selector',
  templateUrl: './goal-selector.component.html',
  styleUrls: ['./goal-selector.component.scss'],
})
export class GoalSelectorComponent implements OnInit {
  private static DUMMY_GOAL_TYPES = ['major']; // TODO Make this dynamic based on school

  @Input() readonly initialGoals: RequirementSet[]; // Optional
  @Output() selectGoals: EventEmitter<RequirementSet[]>;

  requirementSets: RequirementSet[];

  searchPrompt: string;

  selectionStates: GoalSelectionState[];

  constructor(private requirementService: RequirementService) {
    this.selectGoals = new EventEmitter<RequirementSet[]>();
    this.searchPrompt = '';
  }

  /**
   * For each of the goal types, create a state that tracks whether anything has been selected by the user and then
   * import any goals that have been selected previously.
   */
  ngOnInit(): void {
    this.selectionStates = [];
    GoalSelectorComponent.DUMMY_GOAL_TYPES.forEach((goalType: string) => {
      const state = new GoalSelectionState(goalType);
      this.selectionStates.push(state);

      if (this.initialGoals) {
        // Add initial goals to each chosen goals state
        state.chosenGoals = new Set<RequirementSet>(
          this.initialGoals.filter((initialGoal: RequirementSet) => initialGoal.type === goalType),
        );
      }
    });

    this.requirementService.getRequirements().subscribe((requirementSets: RequirementSet[]) => {
      this.requirementSets = requirementSets;
      this.updateGoalSearch();
    });
  }

  /**
   * Updates {@link GoalSelectionState#searchedGoals} for each state so that it contains only goals that match the
   * specifications of {@link GoalSelectorComponent#searchFunction}.
   */
  updateGoalSearch(): void {
    this.selectionStates.forEach((state: GoalSelectionState) => {
      state.searchedGoals = this.requirementSets.filter(
        (goal: RequirementSet) =>
          goal.type === state.type && this.searchFunction(this.searchPrompt, goal) && !state.chosenGoals.has(goal),
      );
    });
    // might make more sense to do the major minor sorting onInit only once and store it
  }

  addGoal(goal: RequirementSet, state: GoalSelectionState): void {
    state.chosenGoals.add(goal);
    state.selectedSearchedGoal = null;
    this.updateGoalSearch();
  }

  removeGoal(goal: RequirementSet, state: GoalSelectionState): void {
    state.chosenGoals.delete(goal);
    state.selectedChosenGoal = null;
    this.updateGoalSearch();
  }

  emitGoals(): void {
    this.selectGoals.emit(this.selectionStates.flatMap((state: GoalSelectionState) => Array.from(state.chosenGoals)));
  }

  private searchFunction(prompt: string, goal: RequirementSet): boolean {
    return goal
      ? goal.id.includes(prompt) || goal.name.includes(prompt) || this.searchFunction(prompt, goal.parent)
      : false;
  }
}

<ng-container *ngIf="requirementSets; else loading">
  <div class="row">
    <div class="col search">
      <div class="form-group">
        <input
          class="form-control"
          type="text"
          placeholder="Search for a major"
          [(ngModel)]="searchPrompt"
          (keyup)="updateGoalSearch()"
        />
      </div>
      <div class="row">
        <div *ngFor="let state of selectionStates" class="form-group col">
          <h4 *ngIf="selectionStates.length > 1">{{ state.type | titlecase }}</h4>
          <div class="form-group">
            <select class="custom-select" size="8" [(ngModel)]="state.selectedSearchedGoal">
              <option *ngFor="let goal of state.searchedGoals" [ngValue]="goal">{{ goal.name }}</option>
            </select>
          </div>
          <div class="form-group">
            <button
              class="btn btn-outline-primary btn-sm btn-block"
              (click)="addGoal(state.selectedSearchedGoal, state)"
              [disabled]="!state.selectedSearchedGoal"
            >
              Add
            </button>
            <span class="request-major">
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://forms.gle/mR4oDS9gKjSRDRYP8"
              >Don't see your major?</a>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-auto">
      <div class="line"></div>
    </div>
    <div class="col">
      <h4 class="gt-modal-header">Selected Goals</h4>
      <div *ngFor="let state of selectionStates">
        <h4 *ngIf="selectionStates.length > 1">{{ state.type | titlecase }}</h4>
        <hr />
        <div *ngFor="let goal of state.chosenGoals">
          <i class="material-icons remove" (click)="removeGoal(goal, state)">close</i>
          <span class="goal">{{ goal.name }}</span>
          <hr />
        </div>
      </div>
      <button class="btn btn-primary btn-sm btn-block" (click)="emitGoals()">Confirm</button>
    </div>
  </div>
</ng-container>
<ng-template #loading>
  Loading...
</ng-template>

// src/client/components/GoalSelector.tsx
import React from 'react';
import { Button, Col, Form, Row } from 'react-bootstrap';

import Requirements from '../lib/requirements';
import { RequirementSet } from '../models/requirement-set.model';

import './GoalSelector.css';

type GoalSelectorProps = {
  initialGoals: RequirementSet[];
  onSelectGoals: (goals: RequirementSet[]) => void;
};

type GoalSelectorState = {
  requirementsMap: Map<string, RequirementSet>;
  searchTerm: string;
  selections: {
    [goalType: string]: {
      selected: RequirementSet;
      goals: RequirementSet[];
    };
  };
};

const GOAL_TYPES = ['major'];

class GoalSelector extends React.Component<GoalSelectorProps, GoalSelectorState> {
  private readonly goalRefs: Map<string, React.RefObject<HTMLSelectElement>>;

  constructor(props: GoalSelectorProps) {
    super(props);

    this.goalRefs = new Map<string, React.RefObject<HTMLSelectElement>>(
      GOAL_TYPES.map((goalType) => [goalType, React.createRef<HTMLSelectElement>()]),
    );

    this.state = {
      requirementsMap: null,
      searchTerm: '',
      selections: Object.fromEntries(
        GOAL_TYPES.map((goalType) => [
          goalType,
          {
            selected: null,
            goals: this.props.initialGoals.filter((goal) => goal.type === goalType),
          },
        ]),
      ),
    };
  }

  componentDidMount(): void {
    this.fetchRequirements();
  }

  private fetchRequirements = async (): Promise<void> => {
    const requirementsMap = await Requirements.getRequirementsMap();
    this.setState({
      requirementsMap,
    });
  };

  handleSelectChange = (): void => {
    this.setState({
      selections: Object.fromEntries(
        Object.entries(this.state.selections).map(([goalType, selection]) => [
          goalType,
          {
            ...selection,
            selected: this.state.requirementsMap.get(this.goalRefs.get(goalType).current.value),
          },
        ]),
      ),
    });
  };

  handleAddGoal = (): void => {
    this.setState({
      selections: Object.fromEntries(
        Object.entries(this.state.selections).map(([goalType, selection]) => [
          goalType,
          selection.selected ? { selected: null, goals: [...selection.goals, selection.selected] } : selection,
        ]),
      ),
    });
  };

  handleRemoveGoal = (goal: RequirementSet): void => {
    this.setState({
      selections: {
        ...this.state.selections,
        [goal.type]: {
          ...this.state.selections[goal.type],
          goals: this.state.selections[goal.type].goals.filter((g) => g !== goal),
        },
      },
    });
  };

  handleSubmit = (): void => {
    this.props.onSelectGoals(
      Object.values(this.state.selections)
        .map((selection) => selection.goals)
        .flat(),
    );
  };

  // TODO This should probably be memoized.
  private getGoalsForType = (goalType: string, requirementSets: Map<string, RequirementSet>): RequirementSet[] => {
    return Array.from(requirementSets.values()).filter((reqSet) => reqSet.type === goalType);
  };

  private searchFunction = (goal: RequirementSet): boolean => {
    /* Hide goals that are already selected. */
    if (!this.state.selections[goal.type] || this.state.selections[goal.type].goals.includes(goal)) {
      return false;
    }
    return goal
      ? goal.id.includes(this.state.searchTerm) ||
          goal.name.includes(this.state.searchTerm) ||
          this.searchFunction(goal.parent)
      : false;
  };

  render(): React.ReactElement {
    if (!this.state.requirementsMap) {
      return <>Loading...</>;
    }

    return (
      <Row>
        <Col className="GoalSelector__search">
          <Form.Group as={Row}>
            <Col>
              <Form.Control
                type="text"
                placeholder="Search for a major"
                onChange={(e) => this.setState({ searchTerm: e.target.value })}
              />
            </Col>
          </Form.Group>
          <Row>
            {GOAL_TYPES.map((goalType) => (
              <Form.Group key={goalType} as={Col}>
                {GOAL_TYPES.length > 1 ? <h4>{goalType}</h4> : null}
                <Form.Group>
                  <Form.Control
                    as="select"
                    htmlSize={8}
                    onChange={this.handleSelectChange}
                    ref={this.goalRefs.get(goalType)}
                  >
                    {this.getGoalsForType(goalType, this.state.requirementsMap)
                      .filter(this.searchFunction)
                      .map((goal) => (
                        <option key={goal.id} value={goal.id}>
                          {goal.name}
                        </option>
                      ))}
                  </Form.Control>
                </Form.Group>
                <Form.Group>
                  <Button
                    variant="outline-primary"
                    size="sm"
                    block
                    onClick={this.handleAddGoal}
                    disabled={!this.state.selections[goalType].selected}
                  >
                    Add
                  </Button>
                  <span className="GoalSelector__request-major">
                    <a
                      href="https://docs.google.com/forms/d/e/1FAIpQLScWm1kJjcBs5eX-j_HejtM_9iV3CgP4VlgoVz4hm1PX8u9vww/viewform"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      Don&rsquo;t see your major?
                    </a>
                  </span>
                </Form.Group>
              </Form.Group>
            ))}
          </Row>
        </Col>
        <Col xs="auto">
          <div className="GoalSelector__line" />
        </Col>
        <Col>
          <h4 className="gt-modal-header">Selected Goals</h4>
          {GOAL_TYPES.map((goalType) => (
            <div key={goalType}>
              {GOAL_TYPES.length > 1 ? <h4>{goalType}</h4> : null}
              <hr />
              {this.state.selections[goalType].goals.map((goal) => (
                <div key={goal.id}>
                  <i className="material-icons GoalSelector__remove" onClick={() => this.handleRemoveGoal(goal)}>
                    close
                  </i>
                  <span className="GoalSelector__goal">{goal.name}</span>
                  <hr />
                </div>
              ))}
            </div>
          ))}
          <Button variant="primary" size="sm" block onClick={this.handleSubmit}>
            Confirm
          </Button>
        </Col>
      </Row>
    );
  }
}

export default GoalSelector;
