// src/client/components/RequirementComponent.tsx
import React from 'react';
import { Dropdown, Modal } from 'react-bootstrap';

import { ProcessedFulfillmentType } from '../lib/process-requirements';
import { Requirement } from '../models/requirement.model';
import { CountRequirement } from '../models/requirements/count-requirement.model';
import { MultiRequirement } from '../models/requirements/multi-requirement.model';
import { PolyRequirement } from '../models/requirements/poly-requirement.model';
import { StandaloneRequirement } from '../models/requirements/standalone-requirement.model';
import { UnitRequirement } from '../models/requirements/unit-requirement.model';
import RequirementDisplay from './RequirementDisplay';

import './RequirementComponent.css';

type RequirementComponentProps = {
  requirement: Requirement;
  fulfillmentMap: Map<Requirement, ProcessedFulfillmentType>;
  onManualFulfill: (req: Requirement) => void;
  onManualUnfulfill: (req: Requirement) => void;
};

type RequirementComponentState = {
  showDisplay: boolean;
};

class RequirementComponent extends React.Component<RequirementComponentProps, RequirementComponentState> {
  constructor(props: RequirementComponentProps) {
    super(props);

    this.state = {
      showDisplay: false,
    };
  }

  openDisplay = (): void => {
    this.setState({
      showDisplay: true,
    });
  };

  closeDisplay = (): void => {
    this.setState({
      showDisplay: false,
    });
  };

  private getFulfillment = (): ProcessedFulfillmentType => {
    if (!this.props.fulfillmentMap.has(this.props.requirement)) {
      console.error(`Fulfillment map is missing ${this.props.requirement.id}`);
      return {
        status: 'unfulfilled',
        method: 'courses',
        coursesUsed: new Set(),
      };
    }
    return this.props.fulfillmentMap.get(this.props.requirement)!;
  };

  private getDisplayRequirement = (): StandaloneRequirement | null => {
    /* Courses can be displayed for standalone, unit, and count requirements. */
    if (this.props.requirement instanceof StandaloneRequirement) {
      return this.props.requirement;
    } else if (
      this.props.requirement instanceof UnitRequirement ||
      this.props.requirement instanceof CountRequirement
    ) {
      return this.props.requirement.requirement;
    }
    return null;
  };

  private renderReqElem = (): React.ReactNode => {
    // TODO These probably belong in separate files.
    const fulfillment = this.getFulfillment();

    if (
      (this.props.requirement instanceof MultiRequirement || this.props.requirement instanceof PolyRequirement) &&
      !this.props.requirement.hidden
    ) {
      /* Multi-requirement display, showing nested requirements underneath.
       * Hidden requirements do not show this. */
      const numFulfilled = this.props.requirement.requirements.filter(
        (childReq) => this.props.fulfillmentMap.get(childReq)?.status === 'fulfilled',
      ).length;
      let numRequiredText: React.ReactNode;
      switch (this.props.requirement.numRequired) {
        case 1:
          numRequiredText = 'One of';
          break;
        case this.props.requirement.requirements.length:
          numRequiredText = 'All of';
          break;
        default:
          numRequiredText = `${numFulfilled}/${this.props.requirement.numRequired} of`;
          break;
      }
      return (
        <>
          {numRequiredText}
          {(this.props.requirement.requirements as Requirement[]).map((childReq) => (
            <RequirementComponent
              key={childReq.id}
              requirement={childReq}
              fulfillmentMap={this.props.fulfillmentMap}
              onManualFulfill={this.props.onManualFulfill}
              onManualUnfulfill={this.props.onManualUnfulfill}
            />
          ))}
        </>
      );
    } else if (this.props.requirement instanceof UnitRequirement) {
      const fulfillingCourses = fulfillment.method === 'courses' ? Array.from(fulfillment.coursesUsed) : [];
      const fulfilledUnits = fulfillingCourses.map((course) => course.units).reduce((a, b) => a + b, 0);
      return (
        <>
          {fulfilledUnits}/{this.props.requirement.units} Units of {this.props.requirement.name}
          {fulfillingCourses.map((course) => (
            <div key={course.id} className="Requirement Requirement__course">
              {course.getName()}
            </div>
          ))}
        </>
      );
    } else if (this.props.requirement instanceof CountRequirement) {
      const fulfillingCourses = fulfillment.method === 'courses' ? Array.from(fulfillment.coursesUsed) : [];
      return (
        <>
          {this.props.requirement.name}
          {fulfillingCourses.map((course) => (
            <div key={course.id} className="Requirement Requirement__fulfilled">
              {course.getName()}
            </div>
          ))}
          {new Array(this.props.requirement.numRequired - fulfillingCourses.length).fill(null).map((value, index) => (
            <div key={index} className="Requirement Requirement__unfulfilled">
              {this.props.requirement.name}
            </div>
          ))}
        </>
      );
    } else {
      /* Standard requirement. */
      return this.props.requirement.name;
    }
  };

  render(): React.ReactElement {
    const fulfillment = this.getFulfillment();
    const manuallyFulfilled = fulfillment.method === 'manual';

    /* Fulfillment CSS classes. */
    const fulfillments = [`Requirement__${fulfillment.status}`];
    if (fulfillment.method === 'manual') {
      fulfillments.push('Requirement__manual');
    }

    const displayRequirement = this.getDisplayRequirement();

    const rendered = (
      <div className={`Requirement ${fulfillments.join(' ')}`}>
        <Dropdown className="Requirement__more">
          <Dropdown.Toggle className="gt-button" as="button" bsPrefix="unused">
            <i className="material-icons">more_horiz</i>
          </Dropdown.Toggle>
          <Dropdown.Menu>
            {this.getDisplayRequirement() ? (
              <Dropdown.Item onClick={this.openDisplay}>Show Fulfilling Courses</Dropdown.Item>
            ) : null}
            <Dropdown.Item
              onClick={
                !manuallyFulfilled
                  ? () => this.props.onManualFulfill(this.props.requirement)
                  : () => this.props.onManualUnfulfill(this.props.requirement)
              }
            >
              Mark as {!manuallyFulfilled ? 'Fulfilled' : 'Unfulfilled'}
            </Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
        {this.renderReqElem()}
        <Modal size="lg" show={this.state.showDisplay} onHide={this.closeDisplay}>
          <Modal.Body>{displayRequirement ? <RequirementDisplay requirement={displayRequirement} /> : null}</Modal.Body>
        </Modal>
      </div>
    );

    // Annotations removed in v0.2.0 for now.
    // /* Annotation popover. */
    // const annotationText = this.props.requirement.getAnnotation();
    // if (annotationText) {
    //   const annotation = (
    //     <Popover id="requirement-annotation">
    //       <Popover.Content>{annotationText}</Popover.Content>
    //     </Popover>
    //   );
    //   rendered = (
    //     <OverlayTrigger trigger={['hover', 'focus']} overlay={annotation}>
    //       {rendered}
    //     </OverlayTrigger>
    //   );
    // }

    return rendered;
  }
}

export default RequirementComponent;

// client/src/app/planner/components/requirement/requirement.component.ts
import { Component, EventEmitter, Input, OnInit, Output, TemplateRef, ViewChild } from '@angular/core';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { Course } from '../../models/course.model';
import { FulfillmentType, CourseFulfillmentType } from '../../models/fulfillment-type.model';
import { Requirement } from '../../models/requirement.model';
import { MultiRequirement } from '../../models/requirements/multi-requirement.model';
import { UnitRequirement } from '../../models/requirements/unit-requirement.model';
import { PolyRequirement } from '../../models/requirements/poly-requirement.model';
import { StandaloneRequirement } from '../../models/requirements/standalone-requirement.model';
import { CountRequirement } from '../../models/requirements/count-requirement.model';

@Component({
  selector: 'app-requirement',
  templateUrl: './requirement.component.html',
  styleUrls: ['./requirement.component.scss'],
})
export class RequirementComponent implements OnInit {
  @Input() readonly requirement: Requirement;
  @Input() readonly courses: Course[];
  @Input() readonly override: string;
  @Input() readonly manuallyFulfilled: Set<string>;
  @Input() readonly fulfillmentMap: Map<Requirement, FulfillmentType>;
  @Input() readonly coursePoolMap: Map<Requirement, Map<Course, CourseFulfillmentType>>;
  @Output() readonly onManualFulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();
  @Output() readonly onManualUnfulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();

  displayedRequirement: Requirement;

  /* eslint-disable @typescript-eslint/no-explicit-any */
  @ViewChild('standardReq', { static: true }) private standardReq: TemplateRef<any>;
  @ViewChild('multiReq', { static: true }) private multiReq: TemplateRef<any>;
  @ViewChild('unitReq', { static: true }) private unitReq: TemplateRef<any>;
  @ViewChild('tagReq', { static: true }) private tagReq: TemplateRef<any>;
  @ViewChild('requirementDisplayTemplate', { static: false }) private requirementDisplayTemplate: TemplateRef<any>;
  @ViewChild('countReq', { static: true }) private countReq: TemplateRef<any>;
  /* eslint-enable @typescript-eslint/no-explicit-any */

  private requirementDisplayModalReference: NgbModalRef;

  constructor(private modalService: NgbModal) {}

  ngOnInit(): void {}

  isStandalone(): boolean {
    return this.requirement instanceof StandaloneRequirement;
  }

  getStandalone(): StandaloneRequirement {
    if (!this.isStandalone()) {
      throw new Error('Attempted to retreive non-StandaloneRequirement as StandaloneRequirement');
    }
    return this.requirement as StandaloneRequirement;
  }

  isMulti(): boolean {
    return this.requirement instanceof MultiRequirement || this.isPoly();
  }

  isPoly(): boolean {
    return this.requirement instanceof PolyRequirement;
  }

  getMulti(): MultiRequirement {
    if (!this.isMulti()) {
      throw new Error('Attempted to retreive non-MultiRequirement as MultiRequirement');
    }
    return this.requirement as MultiRequirement;
  }

  /**
   * Standalone requirements and unit requirements can show requirement display.
   */
  hasDisplay(): boolean {
    return this.isStandalone() || this.isUnit() || this.isCount();
  }

  getFulfillment(): string[] {
    const fulfillments: string[] = [];
    fulfillments.push(this.fulfillmentMap.get(this.requirement));
    if (this.isManuallyFulfilled()) {
      fulfillments.push('manual');
    }
    return fulfillments;
  }

  isUnit(): boolean {
    return this.requirement instanceof UnitRequirement;
  }

  getUnit(): UnitRequirement {
    if (!this.isUnit()) {
      throw new Error('Attempted to retreive non-UnitRequirement as UnitRequirement');
    }
    return this.requirement as UnitRequirement;
  }

  isCount(): boolean {
    return this.requirement instanceof CountRequirement;
  }

  getCount(): CountRequirement {
    if (!this.isCount()) {
      throw new Error('Attempted to retrieve non-CountRequirement as CountRequirement');
    }
    return this.requirement as CountRequirement;
  }

  /**
   * Returns the HTML template of the requirement based on its type.
   *
   * @return {TemplateRef<any>} The template of the requirement.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  getReqTemplate(): TemplateRef<any> {
    if (this.isMulti()) {
      return this.multiReq;
    }
    if (this.isUnit()) {
      return this.unitReq;
    }
    if (this.isCount()) {
      return this.countReq;
    }
    return this.standardReq;
  }

  getAnnotation(): string {
    /* let annotation: string = this.requirement.getAnnotation();
    if (annotation) {
      annotation = annotation.replace(/\n/g, '<br />');
    }
    return annotation; */
    // TODO Custom annotations system
    return null;
  }

  isManuallyFulfilled(): boolean {
    return this.manuallyFulfilled && this.manuallyFulfilled.has(this.requirement.id);
  }

  manuallyFulfill(requirement: Requirement): void {
    this.onManualFulfill.emit(requirement);
  }

  manuallyUnfulfill(requirement: Requirement): void {
    this.onManualUnfulfill.emit(requirement);
  }

  openRequirementDisplay(requirement: Requirement): void {
    this.displayedRequirement = requirement;
    this.requirementDisplayModalReference = this.modalService.open(this.requirementDisplayTemplate, { size: 'lg' });
  }

  closeRequirementDisplay(): void {
    this.requirementDisplayModalReference.close();
  }
}

<ng-template #standardReq>{{ requirement.name }}<span *ngIf="getAnnotation()">&nbsp;*</span></ng-template>

<ng-template #multiReq>
  <ng-container *ngIf="!getMulti().hidden; else standardReq">
    {{
      getMulti().numRequired === 1
        ? 'One of'
        : getMulti().numRequired === getMulti().requirements.length
        ? 'All of'
        : getMulti().numFulfilled(courses, manuallyFulfilled) + '/' + getMulti().numRequired + ' of'
    }}
    <app-requirement
      *ngFor="let childReq of getMulti().requirements"
      [requirement]="childReq"
      [courses]="courses"
      [manuallyFulfilled]="manuallyFulfilled"
      [fulfillmentMap]="fulfillmentMap"
      (onManualFulfill)="manuallyFulfill($event)"
      (onManualUnfulfill)="manuallyUnfulfill($event)"
    ></app-requirement>
  </ng-container>
</ng-template>

<ng-template #unitReq>
  {{ getUnit().unitsFulfilled(courses) }}/{{ getUnit().units }} units of
  <br />
  {{ getUnit().requirement.toString() }}
  <div class="nested">
    <div class="course" *ngFor="let course of retrieveCoursePoolCourseList(fulfillmentMap, getUnit())">
      {{ course.getName() }}
    </div>
  </div>
</ng-template>

<ng-template #countReq>
  <ng-container *ngIf="!getCount().hidden; else hiddenCount">
    {{ requirement.toString() }}
    <div class="nested">
      <div *ngFor="let course of retrieveCoursePoolCourseList(fulfillmentMap, getCoursePool())">
        <div class="fulfilled" *ngIf="course; else unfulfilledCount">
          {{
            course.getName()
          }}
        </div>
      </div>
      <div *ngFor="let number of countReqResiduals(retrieveCoursePoolCourseList(fulfillmentMap, getCoursePool()))">
        {{
          getCount().requirement.name
          }}
      </div>
    </div>
  </ng-container>
</ng-template>

<ng-template #hiddenCount>
  {{ getCount().countFulfilled(courses) }}/{{ getCount().numRequired }} courses of
  <br />
  {{ getCount().requirement.toString() }}
  <div class="nested">
    <div class="course" *ngFor="let course of retrieveCoursePoolCourseList(fulfillmentMap, getCount())">
      {{ course.getName() }}
    </div>
  </div>
</ng-template>

<div
  class="requirement"
  [ngClass]="getFulfillment()"
  [ngbPopover]="getAnnotation() ? annotation : null"
  [triggers]="getAnnotation() ? 'mouseenter:mouseleave' : null"
>
  <div ngbDropdown class="req-more">
    <button class="gt-button" ngbDropdownToggle><i class="material-icons">more_horiz</i></button>
    <div ngbDropdownMenu>
      <button *ngIf="hasDisplay()" ngbDropdownItem (click)="openRequirementDisplay(requirement)">
        Show Fulfilling Courses
      </button>
      <button *ngIf="!isManuallyFulfilled()" ngbDropdownItem (click)="manuallyFulfill(requirement)">
        Mark as Fulfilled
      </button>
      <button *ngIf="isManuallyFulfilled()" ngbDropdownItem (click)="manuallyUnfulfill(requirement)">
        Mark as Unfulfilled
      </button>
    </div>
  </div>
  <ng-container *ngTemplateOutlet="getReqTemplate()"></ng-container>
</div>

<!-- FIXME This can also be an XSS vector -->
<ng-template #annotation>
  <div [outerHTML]="getAnnotation()"></div>
</ng-template>

<ng-template #requirementDisplayTemplate>
  <div class="modal-body">
    <app-requirement-display [requirementInput]="displayedRequirement"></app-requirement-display>
  </div>
</ng-template>
