// src/client-react/components/Initializer.tsx
import React from 'react';
import { Button, Form } from 'react-bootstrap';

import { RequirementSet } from '../models/requirement-set.model';
import { Semester } from '../models/semester.model';
import { UserData } from '../models/user-data.model';

import GoalSelector from './GoalSelector';

import './Initializer.css';

type InitializerProps = {
  onInitializeData: (userData: UserData) => void;
};

type InitializerState = {
  stage: 'semesters' | 'goals';
  error: string;
};

class Initializer extends React.Component<InitializerProps, InitializerState> {
  private readonly startYearRef: React.RefObject<HTMLSelectElement>;
  private readonly gradYearRef: React.RefObject<HTMLSelectElement>;
  private readonly includeSummersRef: React.RefObject<HTMLInputElement>;

  constructor(props: InitializerProps) {
    super(props);

    this.startYearRef = React.createRef<HTMLSelectElement>();
    this.gradYearRef = React.createRef<HTMLSelectElement>();
    this.includeSummersRef = React.createRef<HTMLInputElement>();

    this.state = {
      stage: 'semesters',
      error: null,
    };
  }

  setStage = (stage: 'semesters' | 'goals'): void => {
    if (stage === 'goals') {
      /* Validate semesters. */
      const startYear = parseInt(this.startYearRef.current.value);
      const gradYear = parseInt(this.gradYearRef.current.value);
      if (!startYear || !gradYear) {
        this.setState({
          error: 'Please fill in all required fields.',
        });
        return;
      }
      if (startYear >= gradYear) {
        this.setState({
          error: 'The start year must be before the year of graduation.',
        });
        return;
      }
    }

    this.setState({
      stage,
      error: null,
    });
  };

  handleSubmit = (goals: RequirementSet[]): void => {
    const startYear = parseInt(this.startYearRef.current.value);
    const gradYear = parseInt(this.gradYearRef.current.value);
    const includeSummers = this.includeSummersRef.current.checked;

    const semesters = this.initializeSemesters(startYear, gradYear, includeSummers);
    this.props.onInitializeData({
      semesters,
      goals,
      manuallyFulfilledReqs: new Map<string, Set<string>>(),
    });
  };

  private initializeSemesters(startYear: number, gradYear: number, includeSummers: boolean): Map<string, Semester[]> {
    const semesters: Map<string, Semester[]> = new Map<string, Semester[]>();
    for (let i: number = startYear; i < gradYear; i += 1) {
      const currSem: Semester[] = [];
      currSem.push(new Semester(`Fall ${i}`));
      currSem.push(new Semester(`Spring ${i + 1}`));
      if (includeSummers) {
        currSem.push(new Semester(`Summer ${i + 1}`));
      }
      semesters.set(`${i}-${i + 1}`, currSem);
    }
    return semesters;
  }

  render(): React.ReactElement {
    return (
      <>
        <div style={{ display: this.state.stage === 'semesters' ? undefined : 'none' }}>
          <h4 className="gt-modal-header">Set Up</h4>
          <Form.Group controlId="Initializer__start-year">
            <Form.Label>Start Year</Form.Label>
            <Form.Control as="select" ref={this.startYearRef}>
              <option value={2015}>2015</option>
              <option value={2016}>2016</option>
              <option value={2017}>2017</option>
              <option value={2018}>2018</option>
              <option value={2019}>2019</option>
              <option value={2020}>2020</option>
              <option value={2021}>2021</option>
            </Form.Control>
          </Form.Group>
          <Form.Group controlId="Initializer__end-year">
            <Form.Label>Graduation Year</Form.Label>
            <Form.Control as="select" ref={this.gradYearRef}>
              <option value={2020}>2020</option>
              <option value={2021}>2021</option>
              <option value={2022}>2022</option>
              <option value={2023}>2023</option>
              <option value={2024}>2024</option>
              <option value={2025}>2025</option>
              <option value={2026}>2026</option>
              <option value={2027}>2027</option>
              <option value={2028}>2028</option>
              <option value={2029}>2029</option>
              <option value={2030}>2030</option>
            </Form.Control>
          </Form.Group>
          <Form.Group controlId="Initializer__include-summers">
            <Form.Check label="Include Summer Semesters?" ref={this.includeSummersRef} />
          </Form.Group>
          <Form.Group className="my-4">
            <Button variant="primary" block onClick={() => this.setStage('goals')}>
              Next
            </Button>
            <span className="Initializer__failure">{this.state.error}</span>
          </Form.Group>
        </div>
        <div style={{ display: this.state.stage === 'goals' ? undefined : 'none' }}>
          <GoalSelector initialGoals={[]} onSelectGoals={this.handleSubmit} />
        </div>
      </>
    );
  }
}

export default Initializer;

// client/src/app/planner/components/initializer/initializer.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { RequirementSet } from '../../models/requirement-set.model';
import { Semester } from '../../models/semester.model';
import { UserData } from '../../models/user-data.model';

@Component({
  selector: 'app-initializer',
  templateUrl: './initializer.component.html',
  styleUrls: ['./initializer.component.scss'],
})
export class InitializerComponent implements OnInit {
  @Output() initializeData: EventEmitter<UserData>;
  startYear: number;
  gradYear: number;
  summer: boolean;
  semesterError: string;
  state: 'semesters' | 'goals';

  constructor() {
    this.initializeData = new EventEmitter<UserData>();
    this.state = 'semesters';
  }

  ngOnInit(): void {}

  next(): void {
    if (!this.startYear || !this.gradYear) {
      this.semesterError = 'Please fill in all required fields.';
      return;
    }
    if (this.startYear >= this.gradYear) {
      this.semesterError = 'The start year must be before the year of graduation.';
      return;
    }
    this.state = 'goals';
  }

  submit(reqSets: RequirementSet[]): void {
    const semesters: Map<string, Semester[]> = this.initializeSemesters(this.startYear, this.gradYear, this.summer);
    this.initializeData.emit(new UserData(semesters, reqSets));
  }

  initializeSemesters(startYear: number, gradYear: number, summer: boolean): Map<string, Semester[]> {
    const semesters: Map<string, Semester[]> = new Map<string, Semester[]>();
    for (let i: number = startYear; i < gradYear; i += 1) {
      const currSem: Semester[] = [];
      currSem.push(new Semester(`Fall ${i}`));
      currSem.push(new Semester(`Spring ${i + 1}`));
      if (summer) {
        currSem.push(new Semester(`Summer ${i + 1}`));
      }
      semesters.set(`${i}-${i + 1}`, currSem);
    }
    return semesters;
  }
}

<ng-container *ngIf="state === 'semesters'">
  <h4 class="header">Set Up</h4>
  <div class="initializer">
    <!-- TODO: implement when minors are implemented -->
    <!-- <div class="form-group">
    <label>Minors</label>
    <input class="form-control" [(ngModel)]="minor" />
  </div> -->
    <div class="form-group">
      <label>Start Year</label>
      <select class="form-control" [(ngModel)]="startYear">
        <option [ngValue]="2015">2015</option>
        <option [ngValue]="2016">2016</option>
        <option [ngValue]="2017">2017</option>
        <option [ngValue]="2018">2018</option>
        <option [ngValue]="2019">2019</option>
        <option [ngValue]="2020">2020</option>
        <option [ngValue]="2021">2021</option>
      </select>
    </div>
    <div class="form-group">
      <label>Graduation Year</label>
      <select class="form-control" [(ngModel)]="gradYear">
        <option [ngValue]="2020">2020</option>
        <option [ngValue]="2021">2021</option>
        <option [ngValue]="2022">2022</option>
        <option [ngValue]="2023">2023</option>
        <option [ngValue]="2024">2024</option>
        <option [ngValue]="2025">2025</option>
        <option [ngValue]="2026">2026</option>
        <option [ngValue]="2027">2027</option>
        <option [ngValue]="2028">2028</option>
        <option [ngValue]="2029">2029</option>
        <option [ngValue]="2030">2030</option>
      </select>
    </div>
    <div class="form-group form-check">
      <input id="summer" class="form-check-input" type="checkbox" [(ngModel)]="summer" />
      <label class="form-check-label" for="summer">Include Summer Semesters?</label>
    </div>
    <div class="form-group my-4">
      <button class="btn btn-primary btn-block" (click)="next()">Next</button>
      <span *ngIf="semesterError" class="failure">{{ semesterError }}</span>
    </div>
  </div>
</ng-container>
<ng-container *ngIf="state === 'goals'">
  <app-goal-selector (selectGoals)="submit($event)"></app-goal-selector>
</ng-container>
