// client/src/app/planner/components/login/login.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { UserService } from '../../services/user.service';

import { validateEmail } from '../../lib/utils';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit {
  @Output('login') private login: EventEmitter<void>;
  @Output('register') private register: EventEmitter<void>;
  @Output('dismiss') private dismissEvent: EventEmitter<void>;

  username: string;
  // FIXME Look into how to securely handle passwords in JS/Angular
  password: string;
  password2: string;

  loginError: string;

  regError: string;
  regEmailMarketing: boolean;
  regUserTesting: boolean;

  loading: boolean;
  registering: boolean;

  constructor(private userService: UserService) {
    this.login = new EventEmitter<void>();
    this.register = new EventEmitter<void>();
    this.dismissEvent = new EventEmitter<void>();
    this.loading = false;
    this.registering = false;
    this.username = '';
    this.password = '';
    this.password2 = '';
    this.loginError = null;
    this.regError = null;
    this.regEmailMarketing = true;
    this.regUserTesting = false;
  }

  ngOnInit(): void {}

  dismiss(): void {
    this.dismissEvent.emit();
  }

  switchMode(): void {
    this.registering = !this.registering;
  }

  submitLogin(): void {
    if (!validateEmail(this.username) || !LoginComponent.validPassword(this.password)) {
      this.loginError = 'Invalid username or password';
      return;
    }

    this.loading = true;

    this.userService.login(this.username, this.password).subscribe((error: string) => {
      if (error) {
        this.loginError = error;
      } else {
        this.login.emit();
      }
      this.loading = false;
    });
  }

  submitRegistration(): void {
    if (!validateEmail(this.username)) {
      this.regError = 'Invalid email address';
      return;
    }
    if (this.password !== this.password2) {
      this.regError = "Password and confirm password fields don't match!";
      return;
    }
    if (!LoginComponent.validPassword(this.password)) {
      this.regError = 'Invalid password';
      return;
    }

    this.loading = true;
    this.regEmailMarketing = true;

    this.userService
      .register(this.username, this.password, this.regEmailMarketing, this.regUserTesting)
      .subscribe((error: string) => {
        if (error) {
          this.regError = error;
          this.loading = false;
        } else {
          this.userService.queryWhoami().subscribe(() => {
            this.register.emit();
            this.loading = false;
          });
        }
      });
  }

  private static validPassword(password: string): boolean {
    return password.length >= 6;
  }
}

<ng-container *ngIf="!registering; else regTemplate">
  <h4 class="header">Login</h4>
  <hr />
  <div class="row text-center">
    <div class="col">
      <a href="/login/google">
        <img
          src="/assets/btn_google_signin_light_normal_web.svg"
          onmousedown="this.setAttribute('src', '/assets/btn_google_signin_light_pressed_web.svg')"
          onmouseup="this.setAttribute('src', '/assets/btn_google_signin_light_normal_web.svg')"
          onmouseout="this.setAttribute('src', '/assets/btn_google_signin_light_normal_web.svg')"
        />
      </a>
    </div>
  </div>
  <hr class="or" />
  <form class="login" (ngSubmit)="submitLogin()">
    <div class="form-group">
      <label>Email</label>
      <input class="form-control" type="text" name="username" [(ngModel)]="username" />
    </div>
    <div class="form-group">
      <label>Password</label>
      <input class="form-control" type="password" name="password" [(ngModel)]="password" />
    </div>
    <div class="form-group my-4">
      <button class="btn btn-primary btn-block" type="submit" [disabled]="loading">
        Login
      </button>
      <ng-container *ngIf="failed">
        <span class="failure">Incorrect username or password.</span>
      </ng-container>
    </div>
  </form>
  <div class="register">
    Don't have an account?
    <a href="#" (click)="$event.preventDefault(); switchMode()">Register</a>
  </div>
  <hr class="or" />
  <div class="skip">
    <a href="#" (click)="$event.preventDefault(); dismiss()">Continue as guest</a>
  </div>
</ng-container>
<ng-template #regTemplate>
  <h4 class="header">Register</h4>
  <hr />
  <div class="row text-center">
    <div class="col">
      <a href="/login/google">
        <img
          src="/assets/btn_google_signin_light_normal_web.svg"
          onmousedown="this.setAttribute('src', '/assets/btn_google_signin_light_pressed_web.svg')"
          onmouseup="this.setAttribute('src', '/assets/btn_google_signin_light_normal_web.svg')"
          onmouseout="this.setAttribute('src', '/assets/btn_google_signin_light_normal_web.svg')"
        />
      </a>
    </div>
  </div>
  <hr class="or" />
  <form class="login" (ngSubmit)="submitRegistration()">
    <div class="form-group">
      <label>Email</label>
      <input class="form-control" type="text" name="username" [(ngModel)]="username" />
    </div>
    <div class="form-group">
      <label>Password</label>
      <input class="form-control" type="password" name="password" [(ngModel)]="password" />
    </div>
    <div class="form-group">
      <label>Confirm Password</label>
      <input class="form-control" type="password" name="password2" [(ngModel)]="password2" />
      <small class="form-text text-muted">Your password must be at least 6 characters.</small>
    </div>
    <div class="form-group">
      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          id="email-marketing"
          name="email-marketing"
          [(ngModel)]="regEmailMarketing"
        />
        <label class="form-check-label" for="email-marketing">
          I would like to subscribe to email updates!
        </label>
      </div>
      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          id="user-testing"
          name="user-testing"
          [(ngModel)]="regUserTesting"
        />
        <label class="form-check-label" for="user-testing">
          I would like to be contacted to help with user testing!
        </label>
      </div>
    </div>
    <div class="form-group my-4">
      <button class="btn btn-primary btn-block" type="submit" [disabled]="loading">
        Register
      </button>
      <small class="form-text text-muted text-center px-3">
        By clicking Register, you agree to GradTrak&lsquo;s
        <a href="https://gradtrak.me/terms/" target="_blank">Terms of Service</a> and
        <a href="https://gradtrak.me/privacy/" target="_blank">Privacy Policy</a>.
      </small>
      <ng-container *ngIf="regError">
        <span class="failure">{{ regError }}</span>
      </ng-container>
    </div>
  </form>
  <div class="register">
    Have an account?
    <a href="#" (click)="$event.preventDefault(); switchMode()">Log In</a>
  </div>
  <hr class="or" />
  <div class="skip">
    <a href="#" (click)="$event.preventDefault(); dismiss()">Continue as guest</a>
  </div>
</ng-template>

// client-react/src/components/Login.tsx
import React from 'react';
import { Button, Form } from 'react-bootstrap';

import { validateEmail } from '../lib/utils';

import googleSigninButton from '../assets/google-signin.svg';

type LoginProps = {
  onLogin: (username: string, password: string) => Promise<string>;
  onRegister: (username: string, password: string, userTesting: boolean) => Promise<string>;
  onDismiss: () => void;
};

type LoginState = {
  loading: boolean;
  registering: boolean;
  error: string;
};

class Login extends React.Component<LoginProps, LoginState> {
  private readonly usernameRef: React.RefObject<HTMLInputElement>;
  private readonly passwordRef: React.RefObject<HTMLInputElement>;
  private readonly password2Ref: React.RefObject<HTMLInputElement>;
  private readonly regUserTestingRef: React.RefObject<HTMLInputElement>;

  constructor(props: LoginProps) {
    super(props);

    this.usernameRef = React.createRef<HTMLInputElement>();
    this.passwordRef = React.createRef<HTMLInputElement>();
    this.password2Ref = React.createRef<HTMLInputElement>();
    this.regUserTestingRef = React.createRef<HTMLInputElement>();

    this.state = {
      loading: false,
      registering: false,
      error: null,
    };
  }

  showLogin = () => {
    this.setState({
      registering: false,
      error: null,
    });
  };

  showRegistration = () => {
    this.setState({
      registering: true,
      error: null,
    });
  };

  handleSubmitLogin = async () => {
    const username = this.usernameRef.current.value;
    const password = this.passwordRef.current.value;

    if (!validateEmail(username) || !Login.validPassword(password)) {
      this.setState({
        error: 'Invalid username or password',
      });
      return;
    }

    this.setState({
      loading: true,
    });

    const err = await this.props.onLogin(username, password);

    if (err) {
      this.setState({
        error: err,
      });
    }

    this.setState({
      loading: false,
    });
  };

  handleSubmitRegistration = async () => {
    const username = this.usernameRef.current.value;
    const password = this.passwordRef.current.value;
    const password2 = this.password2Ref.current.value;
    const userTesting = this.regUserTestingRef.current.checked;

    if (!validateEmail(username)) {
      this.setState({
        error: 'Invalid email address',
      });
      return;
    }
    if (password !== password2) {
      this.setState({
        error: "Password and confirm password fields don't match!",
      });
      return;
    }
    if (!Login.validPassword(password)) {
      this.setState({
        error: 'Invalid password',
      });
      return;
    }

    this.setState({
      loading: true,
    });

    const err = await this.props.onRegister(username, password, userTesting);

    if (err) {
      this.setState({
        error: err,
      });
    }

    this.setState({
      loading: false,
    });
  };

  private static validPassword(password: string): boolean {
    return password.length >= 6;
  }

  render(): React.ReactElement {
    if (!this.state.registering) {
      return (
        <>
          <h4 className="gt-modal-header">Login</h4>
          <div className="row text-center">
            <div className="col">
              <a href="/login/google">
                <img src={googleSigninButton} />
              </a>
            </div>
          </div>
          <hr className="or" />
          <Form
            className="login"
            onSubmit={(e) => {
              e.preventDefault();
              this.handleSubmitLogin();
            }}
          >
            <Form.Group>
              <Form.Label>Email</Form.Label>
              <Form.Control type="text" name="username" ref={this.usernameRef} />
            </Form.Group>
            <Form.Group>
              <Form.Label>Password</Form.Label>
              <Form.Control type="password" name="password" ref={this.passwordRef} />
            </Form.Group>
            <div className="my-4 failure">{this.state.error}</div>
            <Form.Group className="my-4">
              <Button variant="primary" block type="submit" disabled={this.state.loading}>
                Login
              </Button>
            </Form.Group>
          </Form>
          <div className="register">
            Don't have an account?{' '}
            <a href="#" onClick={this.showRegistration}>
              Register
            </a>
          </div>
          <hr className="or" />
          <div className="skip">
            <a href="#" onClick={this.props.onDismiss}>
              Continue as guest
            </a>
          </div>
        </>
      );
    } else {
      return (
        <>
          <h4 className="gt-modal-header">Register</h4>
          <div className="row text-center">
            <div className="col">
              <a href="/login/google">
                <img src={googleSigninButton} />
              </a>
            </div>
          </div>
          <hr className="or" />
          <Form
            className="login"
            onSubmit={(e) => {
              e.preventDefault();
              this.handleSubmitLogin;
            }}
          >
            <Form.Group>
              <Form.Label>Email</Form.Label>
              <Form.Control type="text" name="username" ref={this.usernameRef} />
            </Form.Group>
            <Form.Group>
              <Form.Label>Password</Form.Label>
              <Form.Control type="password" name="password" ref={this.passwordRef} />
            </Form.Group>
            <Form.Group>
              <Form.Label>Confirm Password</Form.Label>
              <Form.Control type="password" name="password2" ref={this.password2Ref} />
              <Form.Text muted>Your password must be at least 6 characters.</Form.Text>
            </Form.Group>
            <Form.Group>
              <Form.Check type="checkbox" label="I'd like to help with user testing!" ref={this.regUserTestingRef} />
            </Form.Group>
            <div className="my-4 failure">{this.state.error}</div>
            <Form.Group className="my-4">
              <Button variant="primary" block type="submit" disabled={this.state.loading}>
                Register
              </Button>
              <Form.Text className="text-center my-2 px-3" muted>
                By clicking Register, I agree to receiving updates on what's new as well as GradTrak&lsquo;s{' '}
                <a href="https://gradtrak.me/terms/" target="_blank">
                  Terms of Service
                </a>{' '}
                and
                <a href="https://gradtrak.me/privacy/" target="_blank">
                  Privacy Policy
                </a>
              </Form.Text>
            </Form.Group>
          </Form>
          <div className="register">
            Have an account?{' '}
            <a href="#" onClick={this.showLogin}>
              Log In
            </a>
          </div>
          <hr className="or" />
          <div className="skip">
            <a href="#" onClick={this.props.onDismiss}>
              Continue as guest
            </a>
          </div>
        </>
      );
    }
  }
}

export default Login;
