// client/src/app/components/requirement-category/requirement-category.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Course } from 'models/course.model';
import { Requirement } from 'models/requirement.model';
import { RequirementCategory } from 'models/requirement-category.model';

@Component({
  selector: 'app-requirement-category',
  templateUrl: './requirement-category.component.html',
  styleUrls: ['./requirement-category.component.scss'],
})
export class RequirementCategoryComponent implements OnInit {
  @Input() readonly requirementCategory: RequirementCategory;
  @Input() readonly courses: Course[];
  @Input() readonly manuallyFulfilled: Set<string>;
  @Output() readonly onManualFulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();
  @Output() readonly onManualUnfulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();

  constructor() {}

  ngOnInit(): void {}
}

<div [ngClass]="collapsed ? 'collapsed' : null">
  <div class="name">
    <i class="button material-icons" (click)="toggleCollapsed()">arrow_drop_down</i>
    {{ requirementCategory.name }}
  </div>
  <div class="requirements">
    <app-requirement
      *ngFor="let requirement of requirementCategory.requirements"
      [requirement]="requirement"
      [courses]="courses"
    ></app-requirement>
  </div>
</div>

// client-react/src/components/RequirementCategoryComponent.tsx
import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';

import { ProcessedFulfillmentType } from '../lib/process-requirements';
import { Course } from '../models/course.model';
import { Requirement } from '../models/requirement.model';
import { RequirementCategory } from '../models/requirement-category.model';

import RequirementComponent from './RequirementComponent';

type RequirementCategoryComponentProps = {
  requirementCategory: RequirementCategory;
  courses: Course[];
  manuallyFulfilled: Set<string>;
  fulfillmentMap: Map<Requirement, ProcessedFulfillmentType>;
  onOpenGoalSelector: () => void;
  onOpenRequirementDisplay: (req: Requirement) => void;
  onManualFulfill: (req: Requirement) => void;
  onManualUnfulfill: (req: Requirement) => void;
};

type RequirementCategoryComponentState = {
  collapsed: boolean;
};

class RequirementCategoryComponent extends React.Component<
  RequirementCategoryComponentProps,
  RequirementCategoryComponentState
> {
  constructor(props: RequirementCategoryComponentProps) {
    super(props);

    this.state = {
      collapsed: false,
    };
  }

  handleToggleCollapsed = (): void => {
    this.setState({
      collapsed: !this.state.collapsed,
    });
  };

  render(): React.ReactElement {
    return (
      <div className={this.state.collapsed ? 'collapsed' : null}>
        <Row className="name">
          <Col className="px-1" xs="auto">
            <i className="dropdown-arrow material-icons" onClick={this.handleToggleCollapsed}>
              arrow_drop_down
            </i>
          </Col>
          <Col className="px-1">{this.props.requirementCategory.name}</Col>
        </Row>
        <div className="requirements">
          {this.props.requirementCategory.requirements.map((req) => (
            <RequirementComponent
              requirement={req}
              courses={this.props.courses}
              manuallyFulfilled={this.props.manuallyFulfilled}
              fulfillmentMap={this.props.fulfillmentMap}
              onOpenGoalSelector={this.props.onOpenGoalSelector}
              onOpenRequirementDisplay={this.props.onOpenRequirementDisplay}
              onManualFulfill={this.props.onManualFulfill}
              onManualUnfulfill={this.props.onManualUnfulfill}
            />
          ))}
        </div>
      </div>
    );
  }
}

export default RequirementCategoryComponent;
