// client-react/src/components/RequirementDisplay.tsx
import React from 'react';

import Courses from '../lib/courses';
import { Course } from '../models/course.model';
import { Requirement } from '../models/requirement.model';

type RequirementDisplayProps = {
  requirement: Requirement;
};

type RequirementDisplayState = {
  courses: Course[];
};

class RequirementDisplay extends React.Component<RequirementDisplayProps, RequirementDisplayState> {
  constructor(props: RequirementDisplayProps) {
    super(props);

    this.setState({
      courses: null,
    });
  }

  private fetchCourses = async (): Promise<void> => {
    const courses = await Courses.getCourses();
    this.setState({
      courses,
    });
  };

  // TODO This should probably be memoimzed.
  private getFulfillingCourses = (req: Requirement, courses: Course[]): Course[] => {
    return courses.filter((course) => req.canFulfill(course));
  };

  render(): React.ReactElement {
    if (!this.state.courses) {
      return <>Loading...</>;
    }

    return (
      <>
        <h3 className="display-title">Eligible Courses</h3>
        <div className="course-list">
          {this.getFulfillingCourses(this.props.requirement, this.state.courses).map((course) => (
            <>
              <h4>{course.toString()}</h4>
              <br />
            </>
          ))}
        </div>
      </>
    );
  }
}

export default RequirementDisplay;

// client/src/app/planner/components/requirement-category/requirement-display/requirement-display.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { Course } from '../../../models/course.model';
import { StandaloneRequirement } from '../../../models/requirements/standalone-requirement.model';
import { CourseService } from '../../../services/course.service';

@Component({
  selector: 'app-requirement-display',
  templateUrl: './requirement-display.component.html',
  styleUrls: ['./requirement-display.component.scss'],
})
export class RequirementDisplayComponent implements OnInit {
  @Input() requirementInput: StandaloneRequirement;

  constructor(private courseService: CourseService) {}

  ngOnInit(): void {}

  getFulfillingCourses(): Observable<Course[]> {
    return this.courseService.getCourses().pipe(
      map((courses: Course[]) =>
        courses.filter((course) => {
          return this.requirementInput.isFulfilled(course);
        }),
      ),
    );
  }
}

<h3 class="display-title">Eligible Courses</h3>
<div class="course-list">
  <h4 class="courses" *ngFor="let course of getFulfillingCourses() | async">{{ course.toString() }} <br /></h4>
</div>
