// client/src/app/planner/components/requirement-set/requirement-set.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Requirement } from '../../models/requirement.model';
import { StandaloneRequirement } from '../../models/requirements/standalone-requirement.model';
import { RequirementSet } from '../../models/requirement-set.model';
import { UserService } from '../../services/user.service';

import { ProcessedFulfillmentType } from '../../lib/process-requirements';

@Component({
  selector: 'app-requirement-set',
  templateUrl: './requirement-set.component.html',
  styleUrls: ['./requirement-set.component.scss'],
})
export class RequirementSetComponent implements OnInit {
  @Input() readonly requirementSet: RequirementSet;
  @Input() readonly fulfillmentMap: Map<Requirement, ProcessedFulfillmentType>;
  @Output() readonly openRequirementDisplay: EventEmitter<StandaloneRequirement> = new EventEmitter<
    StandaloneRequirement
  >();

  collapsed: boolean;

  constructor(private userService: UserService) {}

  ngOnInit(): void {}

  manuallyFulfill(requirement: Requirement): void {
    this.userService.manuallyFulfill(requirement, this.requirementSet);
  }

  manuallyUnfulfill(requirement: Requirement): void {
    this.userService.manuallyUnfulfill(requirement, this.requirementSet);
  }

  toggleCollapsed(): void {
    this.collapsed = !this.collapsed;
  }
}

<div [ngClass]="collapsed ? 'collapsed' : null">
  <div class="name row">
    <div class="col-auto px-1">
      <i class="dropdown-arrow material-icons" (click)="toggleCollapsed()">arrow_drop_down</i>
    </div>
    <div class="col px-1">
      {{ requirementSet.name }}
    </div>
  </div>
  <div class="requirement-categories">
    <app-requirement-category
      *ngFor="let requirementCategory of requirementSet.requirementCategories"
      [requirementCategory]="requirementCategory"
      [courses]="courses"
      [manuallyFulfilled]="manuallyFulfilled.get(requirementSet.id)"
      [fulfillmentMap]="fulfillmentMap"
      (onManualFulfill)="manuallyFulfill($event)"
      (onManualUnfulfill)="manuallyUnfulfill($event)"
    ></app-requirement-category>
  </div>
</div>

// src/client-react/components/RequirementSetComponent.tsx
import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';

import { ProcessedFulfillmentType } from '../lib/process-requirements';
import { Requirement } from '../models/requirement.model';
import { StandaloneRequirement } from '../models/requirements/standalone-requirement.model';
import { RequirementSet } from '../models/requirement-set.model';

import RequirementCategoryComponent from './RequirementCategoryComponent';

import './RequirementSetComponent.css';

type RequirementSetComponentProps = {
  requirementSet: RequirementSet;
  fulfillmentMap: Map<Requirement, ProcessedFulfillmentType>;
  onOpenGoalSelector: () => void;
  onOpenRequirementDisplay: (req: StandaloneRequirement) => void;
  onManualFulfill: (req: Requirement) => void;
  onManualUnfulfill: (req: Requirement) => void;
};

type RequirementSetComponentState = {
  collapsed: boolean;
};

class RequirementSetComponent extends React.Component<RequirementSetComponentProps, RequirementSetComponentState> {
  constructor(props: RequirementSetComponentProps) {
    super(props);

    this.state = {
      collapsed: false,
    };
  }

  handleToggleCollapsed = (): void => {
    this.setState({
      collapsed: !this.state.collapsed,
    });
  };

  render(): React.ReactElement {
    return (
      <div className={`RequirementSet ${this.state.collapsed ? 'RequirementSet--collapsed' : ''}`}>
        <Row className="RequirementSet__name">
          <Col className="px-1" xs="auto">
            <i className="material-icons RequirementSet__dropdown-arrow" onClick={this.handleToggleCollapsed}>
              arrow_drop_down
            </i>
          </Col>
          <Col className="px-1">{this.props.requirementSet.name}</Col>
        </Row>
        <div className="RequirementSet__requirement-categories">
          {this.props.requirementSet.requirementCategories.map((reqCategory) => (
            <RequirementCategoryComponent
              key={reqCategory.name}
              requirementCategory={reqCategory}
              fulfillmentMap={this.props.fulfillmentMap}
              onOpenGoalSelector={this.props.onOpenGoalSelector}
              onOpenRequirementDisplay={this.props.onOpenRequirementDisplay}
              onManualFulfill={this.props.onManualFulfill}
              onManualUnfulfill={this.props.onManualUnfulfill}
            />
          ))}
        </div>
      </div>
    );
  }
}

export default RequirementSetComponent;
