// client/src/app/planner/components/requirement/requirement.component.ts
import { Component, EventEmitter, Input, OnInit, Output, TemplateRef, ViewChild } from '@angular/core';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { Course } from '../../models/course.model';
import { FulfillmentType, CourseFulfillmentType } from '../../models/fulfillment-type.model';
import { Requirement } from '../../models/requirement.model';
import { MultiRequirement } from '../../models/requirements/multi-requirement.model';
import { UnitRequirement } from '../../models/requirements/unit-requirement.model';
import { PolyRequirement } from '../../models/requirements/poly-requirement.model';
import { StandaloneRequirement } from '../../models/requirements/standalone-requirement.model';
import { CountRequirement } from '../../models/requirements/count-requirement.model';

@Component({
  selector: 'app-requirement',
  templateUrl: './requirement.component.html',
  styleUrls: ['./requirement.component.scss'],
})
export class RequirementComponent implements OnInit {
  @Input() readonly requirement: Requirement;
  @Input() readonly courses: Course[];
  @Input() readonly override: string;
  @Input() readonly manuallyFulfilled: Set<string>;
  @Input() readonly fulfillmentMap: Map<Requirement, FulfillmentType>;
  @Input() readonly coursePoolMap: Map<Requirement, Map<Course, CourseFulfillmentType>>;
  @Output() readonly onManualFulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();
  @Output() readonly onManualUnfulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();

  displayedRequirement: Requirement;

  /* eslint-disable @typescript-eslint/no-explicit-any */
  @ViewChild('standardReq', { static: true }) private standardReq: TemplateRef<any>;
  @ViewChild('multiReq', { static: true }) private multiReq: TemplateRef<any>;
  @ViewChild('unitReq', { static: true }) private unitReq: TemplateRef<any>;
  @ViewChild('tagReq', { static: true }) private tagReq: TemplateRef<any>;
  @ViewChild('requirementDisplayTemplate', { static: false }) private requirementDisplayTemplate: TemplateRef<any>;
  @ViewChild('countReq', { static: true }) private countReq: TemplateRef<any>;
  /* eslint-enable @typescript-eslint/no-explicit-any */

  private requirementDisplayModalReference: NgbModalRef;

  constructor(private modalService: NgbModal) {}

  ngOnInit(): void {}

  isStandalone(): boolean {
    return this.requirement instanceof StandaloneRequirement;
  }

  getStandalone(): StandaloneRequirement {
    if (!this.isStandalone()) {
      throw new Error('Attempted to retreive non-StandaloneRequirement as StandaloneRequirement');
    }
    return this.requirement as StandaloneRequirement;
  }

  isMulti(): boolean {
    return this.requirement instanceof MultiRequirement || this.isPoly();
  }

  isPoly(): boolean {
    return this.requirement instanceof PolyRequirement;
  }

  getMulti(): MultiRequirement {
    if (!this.isMulti()) {
      throw new Error('Attempted to retreive non-MultiRequirement as MultiRequirement');
    }
    return this.requirement as MultiRequirement;
  }

  /**
   * Standalone requirements and unit requirements can show requirement display.
   */
  hasDisplay(): boolean {
    return this.isStandalone() || this.isUnit() || this.isCount();
  }

  getFulfillment(): string[] {
    const fulfillments: string[] = [];
    fulfillments.push(this.fulfillmentMap.get(this.requirement));
    if (this.isManuallyFulfilled()) {
      fulfillments.push('manual');
    }
    return fulfillments;
  }

  isUnit(): boolean {
    return this.requirement instanceof UnitRequirement;
  }

  getUnit(): UnitRequirement {
    if (!this.isUnit()) {
      throw new Error('Attempted to retreive non-UnitRequirement as UnitRequirement');
    }
    return this.requirement as UnitRequirement;
  }

  isCount(): boolean {
    return this.requirement instanceof CountRequirement;
  }

  getCount(): CountRequirement {
    if (!this.isCount()) {
      throw new Error('Attempted to retrieve non-CountRequirement as CountRequirement');
    }
    return this.requirement as CountRequirement;
  }

  /**
   * Returns the HTML template of the requirement based on its type.
   *
   * @return {TemplateRef<any>} The template of the requirement.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  getReqTemplate(): TemplateRef<any> {
    if (this.isMulti()) {
      return this.multiReq;
    }
    if (this.isUnit()) {
      return this.unitReq;
    }
    if (this.isCount()) {
      return this.countReq;
    }
    return this.standardReq;
  }

  getAnnotation(): string {
    /* let annotation: string = this.requirement.getAnnotation();
    if (annotation) {
      annotation = annotation.replace(/\n/g, '<br />');
    }
    return annotation; */
    // TODO Custom annotations system
    return null;
  }

  isManuallyFulfilled(): boolean {
    return this.manuallyFulfilled && this.manuallyFulfilled.has(this.requirement.id);
  }

  manuallyFulfill(requirement: Requirement): void {
    this.onManualFulfill.emit(requirement);
  }

  manuallyUnfulfill(requirement: Requirement): void {
    this.onManualUnfulfill.emit(requirement);
  }

  openRequirementDisplay(requirement: Requirement): void {
    this.displayedRequirement = requirement;
    this.requirementDisplayModalReference = this.modalService.open(this.requirementDisplayTemplate, { size: 'lg' });
  }

  closeRequirementDisplay(): void {
    this.requirementDisplayModalReference.close();
  }
}

<ng-template #standardReq>{{ requirement.name }}<span *ngIf="getAnnotation()">&nbsp;*</span></ng-template>

<ng-template #multiReq>
  <ng-container *ngIf="!getMulti().hidden; else standardReq">
    {{
      getMulti().numRequired === 1
        ? 'One of'
        : getMulti().numRequired === getMulti().requirements.length
        ? 'All of'
        : getMulti().numFulfilled(courses, manuallyFulfilled) + '/' + getMulti().numRequired + ' of'
    }}
    <app-requirement
      *ngFor="let childReq of getMulti().requirements"
      [requirement]="childReq"
      [courses]="courses"
      [manuallyFulfilled]="manuallyFulfilled"
      [fulfillmentMap]="fulfillmentMap"
      (onManualFulfill)="manuallyFulfill($event)"
      (onManualUnfulfill)="manuallyUnfulfill($event)"
    ></app-requirement>
  </ng-container>
</ng-template>

<ng-template #unitReq>
  {{ getUnit().unitsFulfilled(courses) }}/{{ getUnit().units }} units of
  <br />
  {{ getUnit().requirement.toString() }}
  <div class="nested">
    <div class="course" *ngFor="let course of retrieveCoursePoolCourseList(fulfillmentMap, getUnit())">
      {{ course.getName() }}
    </div>
  </div>
</ng-template>

<ng-template #countReq>
  <ng-container *ngIf="!getCount().hidden; else hiddenCount">
    {{ requirement.toString() }}
    <div class="nested">
      <div *ngFor="let course of retrieveCoursePoolCourseList(fulfillmentMap, getCoursePool())">
        <div class="fulfilled" *ngIf="course; else unfulfilledCount">
          {{
            course.getName()
          }}
        </div>
      </div>
      <div *ngFor="let number of countReqResiduals(retrieveCoursePoolCourseList(fulfillmentMap, getCoursePool()))">
        {{
          getCount().requirement.name
          }}
      </div>
    </div>
  </ng-container>
</ng-template>

<ng-template #hiddenCount>
  {{ getCount().countFulfilled(courses) }}/{{ getCount().numRequired }} courses of
  <br />
  {{ getCount().requirement.toString() }}
  <div class="nested">
    <div class="course" *ngFor="let course of retrieveCoursePoolCourseList(fulfillmentMap, getCount())">
      {{ course.getName() }}
    </div>
  </div>
</ng-template>

<div
  class="requirement"
  [ngClass]="getFulfillment()"
  [ngbPopover]="getAnnotation() ? annotation : null"
  [triggers]="getAnnotation() ? 'mouseenter:mouseleave' : null"
>
  <div ngbDropdown class="req-more">
    <button class="gt-button" ngbDropdownToggle><i class="material-icons">more_horiz</i></button>
    <div ngbDropdownMenu>
      <button *ngIf="hasDisplay()" ngbDropdownItem (click)="openRequirementDisplay(requirement)">
        Show Fulfilling Courses
      </button>
      <button *ngIf="!isManuallyFulfilled()" ngbDropdownItem (click)="manuallyFulfill(requirement)">
        Mark as Fulfilled
      </button>
      <button *ngIf="isManuallyFulfilled()" ngbDropdownItem (click)="manuallyUnfulfill(requirement)">
        Mark as Unfulfilled
      </button>
    </div>
  </div>
  <ng-container *ngTemplateOutlet="getReqTemplate()"></ng-container>
</div>

<!-- FIXME This can also be an XSS vector -->
<ng-template #annotation>
  <div [outerHTML]="getAnnotation()"></div>
</ng-template>

<ng-template #requirementDisplayTemplate>
  <div class="modal-body">
    <app-requirement-display [requirementInput]="displayedRequirement"></app-requirement-display>
  </div>
</ng-template>

// src/client-react/components/RequirementComponent.tsx
import React from 'react';
import { Col, Container, Dropdown, OverlayTrigger, Popover, Row } from 'react-bootstrap';

import { ProcessedFulfillmentType } from '../lib/process-requirements';
import { Course } from '../models/course.model';
import { Requirement } from '../models/requirement.model';
import { CountRequirement } from '../models/requirements/count-requirement.model';
import { MultiRequirement } from '../models/requirements/multi-requirement.model';
import { PolyRequirement } from '../models/requirements/poly-requirement.model';
import { StandaloneRequirement } from '../models/requirements/standalone-requirement.model';
import { UnitRequirement } from '../models/requirements/unit-requirement.model';

import './RequirementComponent.css';

type RequirementComponentProps = {
  requirement: Requirement;
  fulfillmentMap: Map<Requirement, ProcessedFulfillmentType>;
  onOpenGoalSelector: () => void;
  onOpenRequirementDisplay: (req: StandaloneRequirement) => void;
  onManualFulfill: (req: Requirement) => void;
  onManualUnfulfill: (req: Requirement) => void;
};

function RequirementComponent(props: RequirementComponentProps): React.ReactElement {
  const fulfillment = props.fulfillmentMap.get(props.requirement);
  const manuallyFulfilled = fulfillment.method === 'manual';

  /* Fulfillment CSS classes. */
  const fulfillments: string[] = [`Requirement__${fulfillment.status}`];
  if (fulfillment.method === 'manual') {
    fulfillments.push('Requirement__manual');
  }

  /* Courses can be displayed for standalone, unit, and count requirements. */
  let displayRequirement: StandaloneRequirement = null;
  if (props.requirement instanceof StandaloneRequirement) {
    displayRequirement = props.requirement;
  } else if (props.requirement instanceof UnitRequirement || props.requirement instanceof CountRequirement) {
    displayRequirement = props.requirement.requirement;
  }

  /* Requirement element based on the requirement type. */
  // TODO This probably belongs in separate files.
  let reqElem: React.ReactElement = null;
  if (
    (props.requirement instanceof MultiRequirement || props.requirement instanceof PolyRequirement) &&
    !props.requirement.hidden
  ) {
    /* Multi-requirement display, showing nested requirements underneath.
     * Hidden requirements do not show this. */
    const numFulfilled = props.requirement.requirements.filter((childReq) => fulfillment.status === 'fulfilled').length;
    reqElem = (
      <>
        {props.requirement.numRequired === 1
          ? 'One of'
          : props.requirement.numRequired === props.requirement.requirements.length
          ? 'All of'
          : numFulfilled + '/' + props.requirement.numRequired + ' of'}
        {(props.requirement.requirements as Requirement[]).map((childReq) => (
          <RequirementComponent
            key={childReq.id}
            requirement={childReq}
            fulfillmentMap={props.fulfillmentMap}
            onOpenGoalSelector={props.onOpenGoalSelector}
            onOpenRequirementDisplay={props.onOpenRequirementDisplay}
            onManualFulfill={props.onManualFulfill}
            onManualUnfulfill={props.onManualUnfulfill}
          />
        ))}
      </>
    );
  } else if (props.requirement instanceof UnitRequirement) {
    const fulfillingCourses = fulfillment.method === 'courses' ? Array.from(fulfillment.coursesUsed) : [];
    const fulfilledUnits = fulfillingCourses.map((course) => course.units).reduce((a, b) => a + b, 0);
    reqElem = (
      <>
        {fulfilledUnits}/{props.requirement.units} units of {props.requirement.name}
        {fulfillingCourses.map((course) => (
          <div key={course.id} className="Requirement Requirement__course">
            {course.getName()}
          </div>
        ))}
      </>
    );
  } else if (props.requirement instanceof CountRequirement) {
    const fulfillingCourses = fulfillment.method === 'courses' ? Array.from(fulfillment.coursesUsed) : [];
    reqElem = (
      <>
        {props.requirement.name}
        {fulfillingCourses.map((course) => (
          <div key={course.id} className="Requirement Requirement__fulfilled">
            {course.getName()}
          </div>
        ))}
        {new Array(props.requirement.numRequired - fulfillingCourses.length).fill(null).map((value, index) => (
          <div key={index} className="Requirement Requirement__unfulfilled">
            {props.requirement.name}
          </div>
        ))}
      </>
    );
  } else {
    /* Standard requirement. */
    reqElem = <>{props.requirement.name}</>;
  }

  let rendered = (
    <div className={`Requirement ${fulfillments.join(' ')}`}>
      <Dropdown className="Requirement__more">
        <Dropdown.Toggle className="gt-button" as="button" bsPrefix="unused">
          <i className="material-icons">more_horiz</i>
        </Dropdown.Toggle>
        <Dropdown.Menu>
          {displayRequirement ? (
            <Dropdown.Item onClick={() => props.onOpenRequirementDisplay(displayRequirement)}>
              Show Fulfilling Courses
            </Dropdown.Item>
          ) : null}
          <Dropdown.Item
            onClick={
              !manuallyFulfilled
                ? () => props.onManualFulfill(props.requirement)
                : () => props.onManualUnfulfill(props.requirement)
            }
          >
            Mark as {!manuallyFulfilled ? 'Fulfilled' : 'Unfulfilled'}
          </Dropdown.Item>
        </Dropdown.Menu>
      </Dropdown>
      {reqElem}
    </div>
  );

  /* Annotation popover. */
  const annotationText = props.requirement.getAnnotation();
  if (annotationText) {
    const annotation = (
      <Popover id="requirement-annotation">
        <Popover.Content>{annotationText}</Popover.Content>
      </Popover>
    );
    rendered = (
      <OverlayTrigger trigger={['hover', 'focus']} overlay={annotation}>
        {rendered}
      </OverlayTrigger>
    );
  }

  return rendered;
}

export default RequirementComponent;
