// client/src/app/planner/components/requirement-category/requirement-category.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Course } from '../../models/course.model';
import { Requirement } from '../../models/requirement.model';
import { RequirementCategory } from '../../models/requirement-category.model';

import { ProcessedFulfillmentType } from '../../lib/process-requirements';

@Component({
  selector: 'app-requirement-category',
  templateUrl: './requirement-category.component.html',
  styleUrls: ['./requirement-category.component.scss'],
})
export class RequirementCategoryComponent implements OnInit {
  @Input() readonly requirementCategory: RequirementCategory;
  @Input() readonly courses: Course[];
  @Input() readonly manuallyFulfilled: Set<string>;
  @Input() readonly fulfillmentMap: Map<Requirement, ProcessedFulfillmentType>;
  @Output() readonly onManualFulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();
  @Output() readonly onManualUnfulfill: EventEmitter<Requirement> = new EventEmitter<Requirement>();

  collapsed: boolean;

  constructor() {}

  ngOnInit(): void {}

  toggleCollapsed(): void {
    this.collapsed = !this.collapsed;
  }
}

<div [ngClass]="collapsed ? 'collapsed' : null">
  <div class="name row">
    <div class="col-auto px-1">
      <i class="dropdown-arrow material-icons" (click)="toggleCollapsed()">arrow_drop_down</i>
    </div>
    <div class="col px-1">
      {{ requirementCategory.name }}
    </div>
  </div>
  <div class="requirements">
    <app-requirement
      *ngFor="let requirement of requirementCategory.requirements"
      [requirement]="requirement"
      [courses]="courses"
      [manuallyFulfilled]="manuallyFulfilled"
      [fulfillmentMap]="fulfillmentMap"
      (onManualFulfill)="onManualFulfill.emit($event)"
      (onManualUnfulfill)="onManualUnfulfill.emit($event)"
      (openRequirementDisplay)="openRequirementDisplay.emit($event)"
    ></app-requirement>
  </div>
</div>

// src/client-react/components/RequirementCategoryComponent.tsx
import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';

import { ProcessedFulfillmentType } from '../lib/process-requirements';
import { Course } from '../models/course.model';
import { Requirement } from '../models/requirement.model';
import { RequirementCategory } from '../models/requirement-category.model';

import RequirementComponent from './RequirementComponent';

import './RequirementCategoryComponent.css';

type RequirementCategoryComponentProps = {
  requirementCategory: RequirementCategory;
  courses: Course[];
  manuallyFulfilled: Set<string>;
  fulfillmentMap: Map<Requirement, ProcessedFulfillmentType>;
  onOpenGoalSelector: () => void;
  onOpenRequirementDisplay: (req: Requirement) => void;
  onManualFulfill: (req: Requirement) => void;
  onManualUnfulfill: (req: Requirement) => void;
};

type RequirementCategoryComponentState = {
  collapsed: boolean;
};

class RequirementCategoryComponent extends React.Component<
  RequirementCategoryComponentProps,
  RequirementCategoryComponentState
> {
  constructor(props: RequirementCategoryComponentProps) {
    super(props);

    this.state = {
      collapsed: false,
    };
  }

  handleToggleCollapsed = (): void => {
    this.setState({
      collapsed: !this.state.collapsed,
    });
  };

  render(): React.ReactElement {
    return (
      <div className={`RequirementCategory ${this.state.collapsed ? 'RequirementCategory--collapsed' : ''}`}>
        <Row className="RequirementCategory__name">
          <Col className="px-1" xs="auto">
            <i className="material-icons RequirementCategory__dropdown-arrow" onClick={this.handleToggleCollapsed}>
              arrow_drop_down
            </i>
          </Col>
          <Col className="px-1">{this.props.requirementCategory.name}</Col>
        </Row>
        <div className="RequirementCategory__requirements">
          {this.props.requirementCategory.requirements.map((req) => (
            <RequirementComponent
              key={req.id}
              requirement={req}
              courses={this.props.courses}
              manuallyFulfilled={this.props.manuallyFulfilled}
              fulfillmentMap={this.props.fulfillmentMap}
              onOpenGoalSelector={this.props.onOpenGoalSelector}
              onOpenRequirementDisplay={this.props.onOpenRequirementDisplay}
              onManualFulfill={this.props.onManualFulfill}
              onManualUnfulfill={this.props.onManualUnfulfill}
            />
          ))}
        </div>
      </div>
    );
  }
}

export default RequirementCategoryComponent;
