// client/src/app/planner/components/semester-pane/semester-pane.component.ts
import { Component, Input, OnInit, ViewChild, TemplateRef } from '@angular/core';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { Semester } from '../../models/semester.model';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-semester-pane',
  templateUrl: './semester-pane.component.html',
  styleUrls: ['./semester-pane.component.scss'],
})
export class SemesterPaneComponent implements OnInit {
  @Input() readonly semesters: Map<string, Semester[]>;
  semesterArr: Semester[];

  @ViewChild('semesterChangerTemplate', { static: false }) private semesterChangerTemplate: TemplateRef<any>; // eslint-disable-line @typescript-eslint/no-explicit-any
  private semesterChangerModalReference: NgbModalRef;

  constructor(private modalService: NgbModal, private userService: UserService) {}

  ngOnInit(): void {}

  openSemesterChanger(): void {
    this.semesterChangerModalReference = this.modalService.open(this.semesterChangerTemplate, { size: 'lg' });
  }

  closeSemesterChanger(): void {
    this.semesterChangerModalReference.close();
  }

  setSemesters(semestersOutput: Map<string, Semester[]>): void {
    this.userService.updateSemesters(semestersOutput);
  }

  /** Identical to the semesterchanger :(
   * Turns a map of semesters into an array of semesters.
   * @param mapping a mapping of the academic year to their corresponding semesters
   * @return an array of all the semestsers in the values of the map
   */
  getSemArr(mapping: Map<string, Semester[]>): Semester[] {
    return Array.from(mapping.keys())
      .sort()
      .map((key) => mapping.get(key))
      .flat()
      .filter((a) => a);
    // a temporary fix because we haven't implemented view by year functionality yet.
  }
}

<div class="container px-4 py-3">
  <div class="row justify-content-center">
    <div class="col-8 my-4">
      <button class="gt-button gt-button-primary semester-changer" (click)="openSemesterChanger()">
        Edit Semesters
      </button>
    </div>
  </div>
  <div *ngFor="let year of getYears()" class="row">
    <ng-container *ngFor="let semester of getSemArr(semesters)">
      <div *ngIf="semester" class="col-6 semester">
        <app-semester *ngIf="semester" [semester]="semester" [currentSemesters]="getSemArr(semesters)"></app-semester>
      </div>
    </ng-container>
  </div>
</div>

<ng-template #semesterChangerTemplate>
  <div class="modal-body">
    <app-semester-changer
      [semestersInput]="semesters"
      (semesterChanged)="setSemesters($event)"
      (semesterChanged)="closeSemesterChanger()"
    ></app-semester-changer>
  </div>
</ng-template>

// src/client-react/components/SemesterPane.tsx
import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';

import { Course } from '../models/course.model';
import { Semester } from '../models/semester.model';

import SemesterBox from './SemesterBox';

import './SemesterPane.css';

type SemesterPaneProps = {
  semesters: Map<string, Semester[]>;
  onOpenSemesterChanger: () => void;
  onOpenCourseAdder: (semester: Semester) => void;
  onRemoveCourse: (semester: Semester, course: Course) => void;
};

function SemesterPane(props: SemesterPaneProps): React.ReactElement {
  /* Concat all semester-per-year arrays and remove the null ones. */
  const semesterArr = Array.from(props.semesters.keys())
    .sort()
    .map((year) => props.semesters.get(year))
    .flat()
    .filter((semester) => semester);
  // a temporary fix because we haven't implemented view by year functionality yet.

  return (
    // TODO Restore spacing from Angular.
    <Container className="px-4 py-3">
      <Row className="justify-content-center">
        <Col className="my-4" xs={8}>
          <button
            className="gt-button gt-button-primary SemesterPane__semester-changer"
            onClick={props.onOpenSemesterChanger}
          >
            Edit Semesters
          </button>
        </Col>
      </Row>
      <Row>
        {semesterArr.map((semester) => (
          <Col key={semester.name} className="SemesterPane__semester" xs={6}>
            <SemesterBox
              semester={semester}
              currentSemesters={semesterArr}
              onOpenCourseAdder={() => props.onOpenCourseAdder(semester)}
              onRemoveCourse={(course) => props.onRemoveCourse(semester, course)}
            />
          </Col>
        ))}
      </Row>
    </Container>
  );
}

export default SemesterPane;
