// src/client/components/SemesterChanger.tsx
import React from 'react';
import { Button, Col, Form, Row, Modal } from 'react-bootstrap';

import { Semester } from '../models/semester.model';

import './SemesterChanger.css';

type SemesterChangerProps = {
  initialSemesters: Map<string, Semester[]>;
  onChangeSemesters: (semesters: Map<string, Semester[]>) => void;
};

type SemesterChangerState = {
  semesters: Map<string, Semester[]>;
  semesterAdderOpen: boolean;
  error: string;
};

const TERM_INDEX = {
  Fall: 0,
  Spring: 1,
  Summer: 2,
};

class SemesterChanger extends React.Component<SemesterChangerProps, SemesterChangerState> {
  private readonly termRef: React.RefObject<HTMLSelectElement>;
  private readonly yearRef: React.RefObject<HTMLInputElement>;

  constructor(props: SemesterChangerProps) {
    super(props);

    this.termRef = React.createRef<HTMLSelectElement>();
    this.yearRef = React.createRef<HTMLInputElement>();

    this.state = {
      /* Clone map and inner arrays, keeping individual semester references the
       * same. */
      semesters: new Map<string, Semester[]>(
        Array.from(this.props.initialSemesters.entries()).map(([year, sems]) => [year, Array.from(sems)]),
      ),
      semesterAdderOpen: false,
      error: null,
    };
  }

  showSemesterAdder = () => {
    this.setState({
      semesterAdderOpen: true,
    });
  };

  hideSemesterAdder = () => {
    this.setState({
      semesterAdderOpen: false,
    });
  };

  /**
   * Adds the currently requested semester to the current list of semesters.
   *
   * @param {string} semesterName The intended name of the new semester object
   * being initialized. Must be formatted "term YYYY".
   */
  addSemester = (): void => {
    const term = this.termRef.current.value;
    const yearNum = parseInt(this.yearRef.current.value, 10);

    if (!(term && yearNum) || yearNum < 2000 || yearNum > 2050) {
      this.setState({
        error: 'Please select a term and a valid year.',
      });
      return;
    }
    const semesterName: string = `${term} ${yearNum}`;
    if (this.getSemArr().some((semester: Semester) => semester.name === semesterName)) {
      this.setState({
        error: 'This semester is already in your schedule!',
      });
      return;
    }
    const semesters = new Map<string, Semester[]>(this.state.semesters);
    const newSemester = new Semester(semesterName);
    const academicYearName = this.getAcademicYearName(newSemester);
    const semArr = semesterName.split(' ');
    const index = TERM_INDEX[semArr[0]];
    let year: Semester[];
    if (semesters.has(academicYearName)) {
      year = Array.from(semesters.get(academicYearName));
    } else {
      year = [null, null, null];
    }
    year[index] = newSemester;
    semesters.set(academicYearName, year);
    this.setState({
      semesters,
      error: null,
    });
    this.hideSemesterAdder();
  };

  removeSemester = (semester: Semester): void => {
    const semesters = new Map<string, Semester[]>(this.state.semesters);
    const yearName = this.getAcademicYearName(semester);
    const semesterArr = semester.name.split(' ');
    const index = TERM_INDEX[semesterArr[0]];
    const year = Array.from(this.state.semesters.get(yearName));
    year[index] = null;
    if (year.every((yearSem: Semester) => !yearSem)) {
      semesters.delete(yearName);
    } else {
      semesters.set(yearName, year);
    }
    this.setState({
      semesters,
    });
    // an undo button would be nice here. Or an "are you sure".
    // just in case they delete a semester that's important.
  };

  handleSubmit = (): void => {
    this.props.onChangeSemesters(this.state.semesters);
  };

  /**
   * Turns a map of semesters into an array of semesters.
   *
   * @return {Semester[]} An array of all the semestsers in the values of the map
   */
  private getSemArr = (): Semester[] => {
    return Array.from(this.state.semesters.keys())
      .sort()
      .map((key) => this.state.semesters.get(key))
      .flat()
      .filter((a) => a);
  };

  /**
   * Given a semester, retunrs the string of its academic year in the form of
   * 'YYYY-YYYY'
   *
   * @param {string} A semester for which you want the year. Name is in 'term
   * YYYY' format.
   */
  private getAcademicYearName = (semester: Semester): string => {
    const semArr = semester.name.split(' ');
    const semesterYear = parseInt(semArr[1], 10) - (semArr[0] !== 'Fall' ? 1 : 0); // this feels so incredibly clunky.
    return `${semesterYear.toString()}-${(semesterYear + 1).toString()}`; // eg '2019-2020'
  };

  render(): React.ReactElement {
    return (
      <div className="SemesterChanger">
        <h4 className="gt-modal-header">Edit Semesters</h4>
        <div className="SemesterChanger__table">
          {this.getSemArr().map((semester) => (
            <h4 key={semester.name}>
              <i className="material-icons SemesterChanger__remove" onClick={() => this.removeSemester(semester)}>
                close
              </i>
              {semester.name}
            </h4>
          ))}
          <Button variant="primary" size="sm" onClick={this.showSemesterAdder}>
            Add a Semester
          </Button>
        </div>
        <Button variant="primary" onClick={this.handleSubmit}>
          Confirm
        </Button>
        <Modal show={this.state.semesterAdderOpen} onHide={this.hideSemesterAdder}>
          <Modal.Body>
            <h4 className="gt-modal-header">Add a semester</h4>
            <Form
              onSubmit={(e) => {
                e.preventDefault();
                this.addSemester();
              }}
            >
              <Form.Group as={Row}>
                <Col>
                  <Form.Label>Semester</Form.Label>
                </Col>
                <Col>
                  <Form.Control as="select" ref={this.termRef}>
                    <option value="Fall">Fall</option>
                    <option value="Spring">Spring</option>
                    <option value="Summer">Summer</option>
                  </Form.Control>
                </Col>
              </Form.Group>
              <Form.Group as={Row}>
                <Col>
                  <Form.Label>Year</Form.Label>
                </Col>
                <Col>
                  <Form.Control type="number" min="2010" max="2030" ref={this.yearRef} />
                </Col>
              </Form.Group>
              <Form.Group as={Row} className="justify-content-center">
                <Col xs={6}>
                  <Button variant="primary" block type="submit">
                    Add
                  </Button>
                </Col>
              </Form.Group>
              <Form.Group as={Row}>
                <Col className="SemesterChanger__error">{this.state.error}</Col>
              </Form.Group>
            </Form>
          </Modal.Body>
        </Modal>
      </div>
    );
  }
}

export default SemesterChanger;

// client/src/app/planner/components/semester-changer/semester-changer.component.ts
import { Component, EventEmitter, OnInit, Input, Output, ViewChild, TemplateRef } from '@angular/core';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { Semester } from '../../models/semester.model';

@Component({
  selector: 'app-semester-changer',
  templateUrl: './semester-changer.component.html',
  styleUrls: ['./semester-changer.component.scss'],
})
export class SemesterChangerComponent implements OnInit {
  @Input() readonly semestersInput: Map<string, Semester[]>; // optional
  @Output() semesterChanged: EventEmitter<Map<string, Semester[]>>;
  semesters: Map<string, Semester[]>;
  yearNum: number;
  seasonInput: string;
  errorMessage: string = '';
  semesterArr: Semester[];
  SEASON_INDEX: object = {
    Fall: 0,
    Spring: 1,
    Summer: 2,
  };

  @ViewChild('semesterAdder', { static: false }) private referenceToTemplate: TemplateRef<any>; // eslint-disable-line @typescript-eslint/no-explicit-any
  private semesterAdderModal: NgbModalRef;

  constructor(private modalRef: NgbModal) {
    this.semesters = new Map<string, Semester[]>();
    this.semesterChanged = new EventEmitter<Map<string, Semester[]>>();
  }

  ngOnInit(): void {
    if (this.semestersInput) {
      this.semesters = new Map<string, Semester[]>();
      this.semestersInput.forEach((value, key) => {
        this.semesters.set(key, [...value]);
      });
    }
  }

  openSemesterAdder(): void {
    this.semesterAdderModal = this.modalRef.open(this.referenceToTemplate, { size: 'sm' });
  }

  closeSemesterAdder(): void {
    this.semesterAdderModal.close();
  }

  /** Turns a map of semesters into an array of semesters.
   * @param mapping a mapping of the academic year to their corresponding semesters
   * @return an array of all the semestsers in the values of the map
   */
  getSemArr(mapping: Map<string, Semester[]>): Semester[] {
    return Array.from(mapping.values())
      .flat()
      .filter((a) => a);
    // consider making this static. Or just having it not take in args?
  }

  /**
   * Given a semester, retunrs the string of its academic year in the form of
   * 'YYYY-YYYY'
   * @param a semester for which you want the year. Name is in 'Season YYYY' format.
   */

  getAcademicYearName(semester: Semester): string {
    const semArr = semester.name.split(' ');
    const semesterYear = parseInt(semArr[1], 10) - (semArr[0] !== 'Fall' ? 1 : 0); // this feels so incredibly clunky.
    return `${semesterYear.toString()}-${(semesterYear + 1).toString()}`; // eg '2019-2020'
  }

  /**
   * Adds a semester to the current list of semesters.
   *
   * @param {string} semesterName The intended name of the new semester object being initialized.
   * Must be formatted "Season YYYY"
   */
  addSemester(semesterName: string): void {
    if (semesterName.includes('undefined')) {
      this.errorMessage = 'Please select a season and a valid year.';
      return;
    }
    if (
      this.getSemArr(this.semesters)
        .map((semester) => semester.name)
        .includes(semesterName)
    ) {
      this.errorMessage = 'This semester is already in your schedule!';
      return;
    }
    const newSemester = new Semester(semesterName);
    const academicYearName = this.getAcademicYearName(newSemester);
    const semArr = semesterName.split(' ');
    const index = this.SEASON_INDEX[semArr[0]];
    if (this.semesters.get(academicYearName)) {
      this.semesters.get(academicYearName)[index] = newSemester;
    } else {
      this.semesters.set(academicYearName, [null, null, null]);
      this.semesters.get(academicYearName)[index] = newSemester;
    }
    this.closeSemesterAdder(); // optional. We can decide if this is needed.
  }

  /**
   * A helper function that is used to compare two semesters, S1, and S2.
   * semesters that are earlier in time will be smaller than semesters
   * that are later in time. Assumes that semesters are named in the format of
   * "Season 20xx" where season is fall, spring, or summer.
   * @return a numerical value representing the diff.
   */
  semesterCompare(sem1: Semester, sem2: Semester): number {
    const s1 = sem1.name;
    const s2 = sem2.name;
    if (!(s1.includes(' ') || s2.includes(' '))) {
      console.error('a semester is not properly formatted');
      return 0;
    }
    const calcValue = (sem): number => {
      const arr = sem.split(' ');
      if (arr.length !== 2) {
        console.error('a semester is not properly formatted');
        return 0; // don't know what else I can do here. Crash the app?
      }
      const seasonVal =
        {
          // sorry. Just assigning points to each season.
          Spring: '0',
          Summer: '1',
          Fall: '2',
        }[arr[0]] || '3';
      return arr[1] + seasonVal - 0; // sorry nicholas, it's a good meme ok
    };
    return calcValue(s1) - calcValue(s2);
  }

  removeSemester(semester: Semester): void {
    const acadYear = this.getAcademicYearName(semester);
    const semesterArr = semester.name.split(' ');
    const index = this.SEASON_INDEX[semesterArr[0]];
    this.semesters.get(acadYear)[index] = null;
    // an undo button would be nice here. Or an "are you sure".
    // just in case they delete a semester that's important.
  }

  returnSemesters(): void {
    this.semesterChanged.emit(this.semesters);
  }
}

<h4 class="gt-modal-header">Edit Semesters</h4>
<div class="table">
  <h4 *ngFor="let semester of getSemArr()">
    <i class="material-icons" (click)="removeSemester(semester)">close</i>{{ semester.name }}
  </h4>
  <button class="btn btn-primary btn-sm" (click)="openSemesterAdder()">Add a Semester</button>
</div>
<button class="btn btn-primary" (click)="returnSemesters()">Confirm</button>

<ng-template #semesterAdder>
  <div class="modal-body">
    <h4 class="gt-modal-header">Add a semester</h4>
    <form (ngSubmit)="addSemester(termInput, yearNum)">
      <div class="form-group row">
        <div class="col">
          <label>Semester</label>
        </div>
        <div class="col">
          <select class="form-control" name="termInput" type="string" [(ngModel)]="termInput">
            <option ngValue="Fall" selected="selected">Fall</option>
            <!-- TODO selected = selected doesn't actually work for some reason? -->
            <option ngValue="Spring">Spring</option>
            <option ngValue="Summer">Summer</option>
          </select>
        </div>
      </div>
      <div class="form-group row">
        <div class="col">
          <label>Year</label>
        </div>
        <div class="col">
          <input
            class="form-control year-name"
            type="number"
            name="year-name"
            min="2010"
            max="2030"
            [(ngModel)]="yearNum"
          />
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <div class="col-6">
          <button class="btn btn-primary btn-block" type="submit">Add</button>
        </div>
      </div>
      <div class="form-group row">
        <div class="col error">
          {{ errorMessage }}
        </div>
      </div>
    </form>
  </div>
</ng-template>
